### ISSUE TITLE
i just find 1 card after using the tool and checking the tag

### ISSUE THREAD

**Issue by jamesdongdong** [yeqingyan/AnkiAddon#3]
for example, i have 3 card 'a','b','c', and each one has their own duplicate card. 
first I used the tool, and when i checked the tag in the browser, I only found 1 card was taged, such as 'a'.
yes, there is no 'b' and 'c' card which should be taged. 
And after i delete the card 'a' and remove the 'needverify' tag, I use the tool again and I got card 'b' with the 'needverify' tag and 'needremove' tag.

I am not a native speaker and I hope you can understand what I describe above.
please tell me what to do, thank you very much!

**Comment by yeqingyan** [comment]
did you choose the duplicate field? can you export your sample deck into an apkg file and shared it with me? thank you
